---
title: "Outlier"
author: "Haineycf"
date: "December 12, 2016"
output: pdf_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
:

```{r }
library(outliers)
set.seed(1234)
x = rnorm(100)
d=data.frame(x=x,group=rep(1:10,10))
y=runif(5)
z = rnorm(10)
head(x)
head(y)
head(d)
```

check to see if there is 1 outlier, do another test for more than 1
this test is from 1950 and is a quick dirty method for extreme outlier with no known variance

```{r}
chisq.out.test(x)
chisq.out.test(x,opposite=TRUE)
hist(x)
```

to test for outlie or inlie variance, useful for structured data
to determine if they should be separated

```{r}
cochran.test(x~group,d)
cochran.test(x~group,d,inlying=TRUE)
y=runif(5)
head(y)
cochran.test(y,rep(5,5))
cochran.test(y,rep(100,5))

dixon.test(z)
dixon.test(z,opposite=TRUE)
dixon.test(z,type=10)

set.seed(1234)
x = rnorm(10)
grubbs.test(x)
grubbs.test(z,type=20)
grubbs.test(z,type=11)

ox <-outlier(x)

outlier(x,opposite=TRUE)
dim(x) <- c(20,5)
outlier(x)
outlier(x,opposite=TRUE)



qcochran(0.05,5,5)
pcochran(0.293,5,5)


outlier(x)
outlier(x,opposite=TRUE)
rm.outlier(x)
rm.outlier(x,opposite=TRUE)
dim(x) <- c(20,5)
outlier(x)
outlier(x,logical=TRUE)
outlier(x,logical=TRUE,opposite=TRUE)
rm.outlier(x)
rm.outlier(x,opposite=TRUE)


set.seed(1234)
z = rnorm(10)
scores(x)
scores(x,prob=1)
scores(x,prob=0.5)
scores(x,prob=0.1)
scores(x,prob=0.93)
scores(x,type="iqr")
scores(x,type="mad")
scores(x,prob=0)


##############################
##https://www.r-bloggers.com/identify-describe-plot-and-remove-the-outliers-from-the-dataset/
## By Klodian Dhana

outlierKD <- function(dt, var) {
  var_name <- eval(substitute(var),eval(dt))
  na1 <- sum(is.na(var_name))
  m1 <- mean(var_name, na.rm = T)
  par(mfrow=c(2, 2), oma=c(0,0,3,0))
  boxplot(var_name, main="With outliers")
  hist(var_name, main="With outliers", xlab=NA, ylab=NA)
  outlier <- boxplot.stats(var_name)$out
  mo <- mean(outlier)
  var_name <- ifelse(var_name %in% outlier, NA, var_name)
  boxplot(var_name, main="Without outliers")
  hist(var_name, main="Without outliers", xlab=NA, ylab=NA)
  title("Outlier Check", outer=TRUE)
  na2 <- sum(is.na(var_name))
  cat("Outliers identified:", na2 - na1, "n")
  cat("Propotion (%) of outliers:", round((na2 - na1) / sum(!is.na(var_name))*100, 1), "n")
  cat("Mean of the outliers:", round(mo, 2), "n")
  m2 <- mean(var_name, na.rm = T)
  cat("Mean without removing outliers:", round(m1, 2), "n")
  cat("Mean if we remove outliers:", round(m2, 2), "n")
  response <- readline(prompt="Do you want to remove outliers and to replace with NA? [yes/no]: ")
  if(response == "y" | response == "yes"){
    dt[as.character(substitute(var))] <- invisible(var_name)
    assign(as.character(as.list(match.call())$dt), dt, envir = .GlobalEnv)
    cat("Outliers successfully removed", "n")
    return(invisible(dt))
  } else{
    cat("Nothing changed", "n")
    return(invisible(var_name))
  }
}
outlierKD(d, x)  ### need wide screen to show plots
##########################
remove_outliers <- function(x, na.rm = TRUE, ...) {
  qnt <- quantile(x, probs=c(.25, .75), na.rm = na.rm, ...)
  H <- 1.5 * IQR(x, na.rm = na.rm)
  x_rm <- x
  x_rm[x < (qnt[1] - H)] <- NA
  x_rm[x > (qnt[2] + H)] <- NA
  x_rm
}

x <- c(-10, x, 10)
x_rm <- remove_outliers(x)
## png()
par(mfrow = c(1, 2))
boxplot(x)
boxplot(x_rm)
## dev.off()
```

