---
title: "Graph_Examples"
author: "Haineycf"
date: "December 6, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#a dotplot with 2 boxplots  

```{r, echo=FALSE, warning=FALSE}
x1 <-mtcars$mpg
x1_lab <- "Miles Per Gallon"
x2 <- mtcars$disp
x2_lab <-"Disp"
y1 <-mtcars$wt
y1_lab <-"Car Weight"
mainmain <-"Enhanced Scatterplot"
opar<- par(no.readonly = TRUE)
par(fig=c(0,0.8,0,0.8))
plot(x1, y1,
     xlab= x1_lab,
     ylab= y1_lab)
par(fig= c(0,0.8, 0.55, 1), new=TRUE)
boxplot(x1, horizontal = TRUE, axes= FALSE)
par(fig=c(0.65, 1,0,0.8), new= TRUE)
boxplot(y1, axes=FALSE)
mtext(mainmain, side = 3, outer=TRUE, line = -3)
par(opar)

```

# 1 Graph over 2

```{r, echo=FALSE, warning=FALSE}

layout(matrix(c(1,1,2,3), 2,2,byrow= TRUE),
       widths = c(3,1), heights = c(1,2))
hist(y1)
hist(x1)
hist(x2)
```


```{r, echo=FALSE, warning=FALSE}
x= c(1:10)
y <- x
z <- 10/x

opar <-par(no.readonly = TRUE)
par(mfrow=c(1,1), mar=c(5,4,4,8) + 0.1)
plot(x,y, type="b",
     pch=21, col="red",
     yaxt="n", lty=3, ann=FALSE)
lines(x,z, type="b", pch=22, col="blue", lty=2)
axis(2, at=x, labels=x, col.axis="red", las=2)
axis(4, at=z, labels=round(z, digits=2),
     col.axis="blue", las=2, cex.axis=0.7, tck=-.01)
mtext("y=1/x", side=4, line=3, cex.lab=1, las=2, col="blue")
title("An Example of Creative Axes",
      xlab="X values",
      ylab = "Y=X")

par(opar)
```


#pie chart  

```{r, echo=FALSE, warning=FALSE}

par(mfrow= c(2,2))
slices <- c(10,12,4,16,8)
lbls <- c("US", "UK", "Australia", "Germany", "France")
pie(slices, labels = lbls,
    main="Simple Pie Chart")

pct <- round(slices/sum(slices)*100)
lbls2 <- paste(lbls," ", pct, "%", sep= "")
pie(slices, labels= lbls2, col= rainbow(length(lbls2)),
    main="Pie Chart with Percentages")
library(plotrix)
pie3D(slices, labels=lbls, explode =0.1,
      main="3D Pie Chart ")
mytable <- table(state.region)
lbls3 <- paste(names(mytable), "\n", mytable, sep="")
pie(mytable, labels = lbls3,
    main="Pie Chart from a Table \n (with the sample sizes)")
par(mfrow= c(1,1))

```


# ggplot2 pie chart  
```{r, echo=FALSE, warning=FALSE}

df <- data.frame(
  group = c("Male", "Female", "Child"),
  value = c(25, 25, 50)
  )
head(df)

library(ggplot2)
# Barplot
bp<- ggplot(df, aes(x="", y=value, fill=group))+
geom_bar(width = 1, stat = "identity")


pie <- bp + coord_polar("y", start=0)
pie
x <- c(1, 2,3,4,5,6)
y <- c("1","2","3","4","5","6")
par(mar=c(5.1, 4.1, 4.1, 8.1), xpd=TRUE)
pie(x=x, label="", col=rainbow(length(y)), main="Violent Crimes" ) 
legend("topright", inset=c(-1,.2),legend=y, fill=rainbow(length(y)), cex = 0.5)
```

```{r,echo=FALSE, warning=FALSE}
xrange <- range(Orange$age)
yrange <-range(Orange$circumference)

plot(xrange,yrange,
     type ="n",
     xlab ="Age (days)",
     ylab = "Circumference (mm)")

colors <-rainbow(ntrees)
linetype <- c(1:ntrees)
plotchar <-seq(18, 18+ntrees, 1)
for ( i in 1:ntrees){
  tree <-subset(Orange, Tree==i)
  lines(tree$age, tree$circumference,
        type="b",
        lwd=2,
        lty=linetype[i],
        col=colors[i],
        pch=plotchar[i])
}
title("Tree Growth", "edample of line plot")
legend(xrange[i], yrange[2],
       1:ntrees,
       cex=0.8,
       col=colors,
       pch=plotchar,
       lty=linetype,
       title="tree")



```

```{r, echo=FALSE, warning=FALSE}
library(ISwR)
interaction.plot(heart.rate$time,heart.rate$subj,heart.rate$hr)

